#!/bin/sh

# Example for $XDG_CONFIG_HOME/swiv/exec/key-handler
# Called by swiv(1) after the external prefix key (C-x by default) is pressed.
# The next key combo is passed as its first argument. Passed via stdin are the
# images to act upon, one path per line: all marked images, if in thumbnail
# mode and at least one image has been marked, otherwise the current image.
# swiv(1) blocks until this script terminates. It then checks which images
# have been modified and reloads them.

# The key combo argument has the following form: "[C-][M-][S-]KEY",
# where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the xkb
# keysym as listed in /usr/include/xkbcommon/xkbcommon-keysyms.h without the
# "XKB_KEY_" prefix.

case "$1" in
    "C-y") wl-copy -n ;;
    "y") while read file; do wl-copy -t image/png < "$file"; done ;;
    "g") tr '\n' '\0' | xargs -0 gimp & ;;
    "w") set_wallpaper ;;
esac
